# DevOps Pipeline definition for the OFS Beta Widget API 

# The code branch that will trigger a build
trigger:
- release/*

# The pr from branches to be included or excluded to trigger build
pr: none

# Build Agent Resources
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

# Build Process Tree
steps:

  # Enforce Python Version (see above)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'


  - script: |
      pip install --target="$(System.DefaultWorkingDirectory)/.python_packages/lib/site-packages" -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Execute Python Tests
#

  # Archive the Azure Python Function into a ZIP package for deployment
  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
      replaceExistingArchive: true

  # Publish the ZIP package
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
      ArtifactName: 'drop'
